---
title: Quest천es
---

<!--install and/or load all R packages-->
```{r setup, include = FALSE, echo = FALSE, warning = FALSE, message = FALSE, fig.align = 'center', out.width = "100%", results = "hide"}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.align = 'center',
  results = "asis",
  include = TRUE,
  out.width = "100%",
  knitr.kable.NA = '--',
  knitr.table.format = "html"
)
```

```{r try-questoes}
has.questoes <-
  !evaluate::is.error(try(match(list.dirs(getwd()), "Quest천es"),
                silent = TRUE)
  )
```

```{r simuladores, eval = has.questoes}
questoes <- list.files(file.path(getwd(), "Quest천es"), pattern = ".txt")
imagens <- list.files(file.path(getwd(), "Imagens"), pattern = ".png")
respostas <- list.files(file.path(getwd(), "Respostas"), pattern = ".txt")
corretas <- list.files(file.path(getwd(), "Corretas"), pattern = ".txt")

for (i in 1:length(questoes)) {
  cat('\n\n<!-- -->\n\n')
  cat(paste0('# **', as.character(i), '**'))
  cat('\n\n<!-- -->\n\n')
  cat(paste0("**", readLines(file.path(getwd(), "Quest천es", questoes[i])), "**"), sep = "")
  cat('\n\n<!-- -->\n\n')
  opcoes <- readLines(file.path(getwd(), "Respostas", respostas[i]))
  opcoes <- paste0(1:length(opcoes), ") ", opcoes)
  opcoes <- unlist(strsplit(opcoes, split = "\n"))
  cat(paste0(opcoes, "\n"))
  cat('\n\n<!-- -->\n\n')
}
```

<br>
