---
title: Simuladores
output: rmdformats::material
---

<!--install and/or load all R packages-->
```{r setup, include = FALSE, echo = FALSE, warning = FALSE, message = FALSE, fig.align = 'center', out.width = "100%", results = "hide"}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.align = 'center',
  results = "asis",
  include = TRUE,
  out.width = "100%",
  knitr.kable.NA = '--',
  knitr.table.format = "html"
)
```

```{r try-simuladores}
has.simuladores <-
  !evaluate::is.error(try(readxl::read_excel("simuladores.xlsx", sheet = 1),
                silent = TRUE)
  )
```

```{r simuladores, eval = has.simuladores}
simuladores <- readxl::read_excel("simuladores.xlsx",
               sheet = 1,
               col_types = c("text"))

for (i in 1:dim(simuladores)[1]) {
  cat('\n\n<!-- -->\n\n')
  cat(paste0('# **', simuladores[i,1], '**'))
  cat('\n\n<!-- -->\n\n')
  
  cat(
    paste(
      '<iframe src=\"',
      simuladores[i,2],
      '\" style=\"width:100%; height:400px; border:2px solid black;"></iframe>',
      sep = ""
    )
  )
}
```

<br>
